articulo:
    pattern:  /articulo
    defaults: { _controller: "BackendBundle:articulo:index" }

articulo_show:
    pattern:  /articulo/{id}/show
    defaults: { _controller: "BackendBundle:articulo:show" }

articulo_new:
    pattern:  /articulo/new
    defaults: { _controller: "BackendBundle:articulo:new" }

articulo_create:
    pattern:  /articulo/create
    defaults: { _controller: "BackendBundle:articulo:create" }
    requirements: { _method: post }

articulo_edit:
    pattern:  /articulo/{id}/edit
    defaults: { _controller: "BackendBundle:articulo:edit" }

articulo_update:
    pattern:  /articulo/{id}/update
    defaults: { _controller: "BackendBundle:articulo:update" }
    requirements: { _method: post }

articulo_delete:
    pattern:  /articulo/{id}/delete
    defaults: { _controller: "BackendBundle:articulo:delete" }
    requirements: { _method: post }
