cliente:
    pattern:  /cliente
    defaults: { _controller: "BackendBundle:cliente:index" }

cliente_show:
    pattern:  /cliente/{id}/show
    defaults: { _controller: "BackendBundle:cliente:show" }

cliente_new:
    pattern:  /cliente/new
    defaults: { _controller: "BackendBundle:cliente:new" }

cliente_create:
    pattern:  /cliente/create
    defaults: { _controller: "BackendBundle:cliente:create" }
    requirements: { _method: post }

cliente_edit:
    pattern:  /cliente/{id}/edit
    defaults: { _controller: "BackendBundle:cliente:edit" }

cliente_update:
    pattern:  /cliente/{id}/update
    defaults: { _controller: "BackendBundle:cliente:update" }
    requirements: { _method: post }

cliente_delete:
    pattern:  /cliente/{id}/delete
    defaults: { _controller: "BackendBundle:cliente:delete" }
    requirements: { _method: post }
