pedidod:
    pattern:  /pedidod
    defaults: { _controller: "BackendBundle:pedidod:index" }

pedidod_show:
    pattern:  /pedidod/{id}/show
    defaults: { _controller: "BackendBundle:pedidod:show" }

pedidod_new:
    pattern:  /pedidod/new
    defaults: { _controller: "BackendBundle:pedidod:new" }

pedidod_create:
    pattern:  /pedidod/create
    defaults: { _controller: "BackendBundle:pedidod:create" }
    requirements: { _method: post }

pedidod_edit:
    pattern:  /pedidod/{id}/edit
    defaults: { _controller: "BackendBundle:pedidod:edit" }

pedidod_update:
    pattern:  /pedidod/{id}/update
    defaults: { _controller: "BackendBundle:pedidod:update" }
    requirements: { _method: post }

pedidod_delete:
    pattern:  /pedidod/{id}/delete
    defaults: { _controller: "BackendBundle:pedidod:delete" }
    requirements: { _method: post }
