tienda:
    pattern:  /tienda
    defaults: { _controller: "BackendBundle:tienda:index" }

tienda_show:
    pattern:  /tienda/{id}/show
    defaults: { _controller: "BackendBundle:tienda:show" }

tienda_new:
    pattern:  /tienda/new
    defaults: { _controller: "BackendBundle:tienda:new" }

tienda_create:
    pattern:  /tienda/create
    defaults: { _controller: "BackendBundle:tienda:create" }
    requirements: { _method: post }

tienda_edit:
    pattern:  /tienda/{id}/edit
    defaults: { _controller: "BackendBundle:tienda:edit" }

tienda_update:
    pattern:  /tienda/{id}/update
    defaults: { _controller: "BackendBundle:tienda:update" }
    requirements: { _method: post }

tienda_delete:
    pattern:  /tienda/{id}/delete
    defaults: { _controller: "BackendBundle:tienda:delete" }
    requirements: { _method: post }
