# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
BackendBundle:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /
