security:

    acl:
        connection: default
    
    firewalls:
        # Firewall de la parte de administración o backend
        backend:
            pattern:        ^/backend
            provider:       administradores
            http_basic:     ~
     
    access_control:
         - { path: ^/backend/*,         roles: ROLE_ADMIN }
    
    encoders:
         Symfony\Component\Security\Core\User\User: sha512
    
    providers:
        # Usuarios del backend
        administradores:
            users:
                # user = admin, pass = 1234
                admin: { password: Eti36Ru/pWG6WfoIPiDFUBxUuyvgMA4L8+LLuGbGyqV9ATuT9brCWPchBqX5vFTF+DgntacecW+sSGD+GZts2A==, roles: ROLE_ADMIN }
    
    role_hierarchy:
        ROLE_ADMIN: [ROLE_TIENDA, ROLE_USUARIO, ROLE_ALLOWED_TO_SWITCH]
