<?php

namespace Siga21\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * articuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articuloRepository extends EntityRepository
{
public function queryTodosLosArticulos()
{
$em = $this->getEntityManager();
$consulta = $em->createQuery('SELECT o FROM BackendBundle:articulo o');
return $consulta;
}

public function findTodosLosArticulos()
{
return $this->queryTodosLosArticulos()->getResult();
}
}