<?php

namespace Siga21\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * clienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clienteRepository extends EntityRepository
{
}