backend_portada:
    pattern:  /backend
    defaults: { _controller: BackendBundle:Sitio:index}
    
_familia:
    resource: ./routing/familia.yml
_articulo:
    resource: ./routing/articulo.yml
_tienda:
    resource: ./routing/tienda.yml
_cliente:
    resource: ./routing/cliente.yml
_pedidoc:
    resource: ./routing/pedidoc.yml
_pedidod:
    resource: ./routing/pedidod.yml                
